Bootstrap: docker
From: funkey/gunpowder:v0.3.2

%labels

    Maintainer Lisa Mais
    Version 0.1


%setup
mkdir -p ${SINGULARITY_ROOTFS}/neurolight

%files
../neurolight /neurolight/neurolight
../requirements.txt /neurolight/requirements.txt
../setup.py /neurolight/setup.py

%labels
maintainer Lisa.Mais@mdc-berlin.de

%post

# install dependencies

DAISY_ROOT=${SINGULARITY_ROOTFS}/src/daisy
DAISY_REPOSITORY=https://github.com/funkey/daisy
DAISY_REVISION=dc14ee3d5395d9ec2bcaca032d7ed5c5d97f8c70

mkdir -p ${DAISY_ROOT}
cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
pip install -r requirements.txt
PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH

NUMCODECS_ROOT=${SINGULARITY_ROOTFS}/src/numcodecs
NUMCODECS_REPOSITORY=https://github.com/funkey/numcodecs
NUMCODECS_REVISION=f950047d7b666723f81006cbdfd82c0e6705c39c

mkdir -p ${NUMCODECS_ROOT}
cd ${NUMCODECS_ROOT}
git clone ${NUMCODECS_REPOSITORY} . && \
git checkout ${NUMCODECS_REVISION} && \
git submodule update --init --recursive
pip install -r requirements.txt
python setup.py install

ZARR_ROOT=${SINGULARITY_ROOTFS}/src/zarr
ZARR_REPOSITORY=https://github.com/funkey/zarr
ZARR_REVISION=9ddf849a6e3329f5ff361ebf6156712926e2fdfe

mkdir -p ${ZARR_ROOT}
cd ${ZARR_ROOT}
git clone ${ZARR_REPOSITORY} . && \
git checkout ${ZARR_REVISION}
pip install -r requirements.txt
python setup.py install

# install neurolight

cd ${SINGULARITY_ROOTFS}/neurolight
python setup.py install

%environment
export DAISY_ROOT=/src/daisy
export DAISY_REPOSITORY=https://github.com/funkey/daisy
export DAISY_REVISION=dc14ee3d5395d9ec2bcaca032d7ed5c5d97f8c70
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH

%runscript
exec /bin/bash "$@"
